#!/bin/bash -eu
#
# Copyright (C) 2017 Google Inc.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

readonly BLACKLIST_FILE="/tmp/blacklisted_packages.list"

function list_all_packages() {
  dpkg-query -W | cut -f 1 | cut -d ":" -f 1 | sort
}

function list_packages() {
  comm -13 <(sort "${BLACKLIST_FILE}") <(list_all_packages)
}

function list_gpl_packages() {
  for pkg in $(list_packages); do
    if egrep -q '\WGPL\W' "/usr/share/doc/${pkg}/copyright"; then
      echo "${pkg}"
    fi
  done
}

function blacklist_all_current() {
  list_all_packages >> "${BLACKLIST_FILE}"
}

function blacklist_nothing() {
  cat /dev/null > "${BLACKLIST_FILE}"
}

function blacklist() {
  for pkg in $@; do
    echo "${pkg}" >> "${BLACKLIST_FILE}"
  done
}

function download_source_code() {
  local -r target_dir="$1"
  local -r src_list_file="/etc/apt/sources.list.d/all-src.list"

  if ! [[ -e "${BLACKLIST_FILE}" ]]; then
    echo "No package blacklist found. This might download a lot of code."
    echo "If it is really desired, run with argument 'blacklist-nothing' first."
    exit 1
  fi

  # Add all current deb sources as deb-src.
  cat /etc/apt/sources.list /etc/apt/sources.list.d/* \
    | sed 's/^deb /deb-src /g' | sort | uniq \
    > "${src_list_file}"
  apt-get update

  cd "${target_dir}"
  for pkg in $(list_gpl_packages); do
    echo "--> Downloading source code for GPL package ${pkg}..."
    apt-get source -q -d "${pkg}"
  done

  rm "${src_list_file}" "${BLACKLIST_FILE}"
  apt-get update
}

action="$1"
case "${action}" in
  blacklist-all-current)
    blacklist_all_current
    ;;
  blacklist)
    shift
    blacklist "$@"
    ;;
  blacklist-nothing)
    blacklist_nothing
    ;;
  download)
    shift
    download_source_code "$1"
    ;;
  *)
    echo "Usage:"
    echo "  blacklist-all-current"
    echo "    Add all currently installed packages into the blacklist."
    echo "  blacklist PACKAGE_NAME..."
    echo "    Explicitly add specific package names into the blacklist."
    echo "  blacklist-nothing"
    echo "    Make the blacklist empty."
    echo "  download TARGET_DIRECTORY"
    echo "    Run this to download source code for new GPL packages"
    echo "    that are not in the blacklist."
    exit 1
    ;;
esac
